sh /code/tcrp/created_models/MAML_cmd/subcommands/subcommands_MAML_drugs0.sh
sh /code/tcrp/created_models/MAML_cmd/subcommands/subcommands_MAML_drugs1.sh
sh /code/tcrp/created_models/MAML_cmd/subcommands/subcommands_MAML_drugs2.sh
sh /code/tcrp/created_models/MAML_cmd/subcommands/subcommands_MAML_drugs3.sh
sh /code/tcrp/created_models/MAML_cmd/subcommands/subcommands_MAML_drugs4.sh
sh /code/tcrp/created_models/MAML_cmd/subcommands/subcommands_MAML_drugs5.sh
sh /code/tcrp/created_models/MAML_cmd/subcommands/subcommands_MAML_drugs6.sh
sh /code/tcrp/created_models/MAML_cmd/subcommands/subcommands_MAML_drugs7.sh
sh /code/tcrp/created_models/MAML_cmd/subcommands/subcommands_MAML_drugs8.sh
sh /code/tcrp/created_models/MAML_cmd/subcommands/subcommands_MAML_drugs9.sh
sh /code/tcrp/created_models/MAML_cmd/subcommands/subcommands_MAML_drugs10.sh
sh /code/tcrp/created_models/MAML_cmd/subcommands/subcommands_MAML_drugs11.sh
sh /code/tcrp/created_models/MAML_cmd/subcommands/subcommands_MAML_drugs12.sh
sh /code/tcrp/created_models/MAML_cmd/subcommands/subcommands_MAML_drugs13.sh
sh /code/tcrp/created_models/MAML_cmd/subcommands/subcommands_MAML_drugs14.sh
sh /code/tcrp/created_models/MAML_cmd/subcommands/subcommands_MAML_drugs15.sh