#!/usr/bin/env bash
set -v 
sh /code/tcrp/created_models/baseline_cmd/subcommands/subcommands_baseline_drugs0.sh
sh /code/tcrp/created_models/baseline_cmd/subcommands/subcommands_baseline_drugs1.sh
sh /code/tcrp/created_models/baseline_cmd/subcommands/subcommands_baseline_drugs2.sh
sh /code/tcrp/created_models/baseline_cmd/subcommands/subcommands_baseline_drugs3.sh
sh /code/tcrp/created_models/baseline_cmd/subcommands/subcommands_baseline_drugs4.sh
sh /code/tcrp/created_models/baseline_cmd/subcommands/subcommands_baseline_drugs5.sh
sh /code/tcrp/created_models/baseline_cmd/subcommands/subcommands_baseline_drugs6.sh
sh /code/tcrp/created_models/baseline_cmd/subcommands/subcommands_baseline_drugs7.sh
sh /code/tcrp/created_models/baseline_cmd/subcommands/subcommands_baseline_drugs8.sh
sh /code/tcrp/created_models/baseline_cmd/subcommands/subcommands_baseline_drugs9.sh
sh /code/tcrp/created_models/baseline_cmd/subcommands/subcommands_baseline_drugs10.sh
sh /code/tcrp/created_models/baseline_cmd/subcommands/subcommands_baseline_drugs11.sh
sh /code/tcrp/created_models/baseline_cmd/subcommands/subcommands_baseline_drugs12.sh
sh /code/tcrp/created_models/baseline_cmd/subcommands/subcommands_baseline_drugs13.sh
sh /code/tcrp/created_models/baseline_cmd/subcommands/subcommands_baseline_drugs14.sh
sh /code/tcrp/created_models/baseline_cmd/subcommands/subcommands_baseline_drugs15.sh
