#!/usr/bin/env bash
set -exv

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
bash tune.sh "$@"

# The previous version of this file was commented-out and follows below:
#
# #!/usr/bin/env bash
# set -exv
# bash /code/MAML_commands.sh
