#!/usr/bin/env bash
set -exv

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
# The previous version of this file was commented-out and follows below:
#
bash /code/tcrp/created_models/PDTC_commands.sh "$@"
# 
