#!/usr/bin/env bash
set -exv

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
# The previous version of this file was commented-out and follows below:
#
bash tcrp/created_models/baseline_cmd/subcommands/subcommands_baseline_drugs0.sh "$@"
# 
